{%set name = "awscli" %}
{%set version = "1.11.24" %}
{%set hash_type = "sha256" %}
{%set hash_val = "c3edb1e15b2b595d40691a716296b464c2cc2ef8cc39269a395e0dbf0f3fcc68" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - botocore ==1.4.81
    - colorama >=0.2.5,<=0.3.7
    - docutils >=0.10
    - rsa >=3.1.2,<=3.5.0
    - s3transfer >=0.1.9,<0.2.0
    - pyyaml >=3.10,<=3.12
    - argparse >=1.1  # [py26]

test:
  imports:
    - awscli
    - awscli.customizations
    - awscli.customizations.cloudtrail
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.ec2
    - awscli.customizations.emr
    - awscli.customizations.gamelift
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy

about:
  home: http://aws.amazon.com/cli/
  license: Apache 2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'Universal Command Line Environment for AWS.'
  dev_url: https://github.com/aws/aws-cli
  doc_url: http://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
