{%set name = "awscli" %}
{%set version = "1.11.63" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "358434e313f742c9cb658aff15c57ce8d3c4b1e1034da71935671ec1d1c60ae5" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - botocore ==1.5.26
    - colorama >=0.2.5,<=0.3.7
    - docutils >=0.10
    - rsa >=3.1.2,<=3.5.0
    - s3transfer >=0.1.9,<0.2.0
    - pyyaml >=3.10,<=3.12
    - argparse >=1.1  # [py26]

test:
  imports:
    - awscli
    - awscli.customizations
    - awscli.customizations.cloudtrail
    - awscli.customizations.codedeploy
    - awscli.customizations.configservice
    - awscli.customizations.configure
    - awscli.customizations.datapipeline
    - awscli.customizations.ec2
    - awscli.customizations.emr
    - awscli.customizations.gamelift
    - awscli.customizations.s3
    - awscli.customizations.s3.syncstrategy

about:
  home: https://aws.amazon.com/cli/
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: Universal Command Line Environment for AWS.
  dev_url: https://github.com/aws/aws-cli
  doc_url: https://aws.amazon.com/cli/

extra:
  recipe-maintainers:
    - pmlandwehr
    - hajapy
