travis:
  secure:
    BINSTAR_TOKEN: LKliVaiUJH6ZroOSEcOq66Of/MQ2EL5vA7lpiR6D11//BXWjo235YC1jqoME5MbgBnvmIiCz34QQJmc7sdOdRW6o1f1klMVld+0CCY7Ojmb36JgHbxu5oxaOrMIhxOVxFOkXKtMDiHU4/xq6/ZWXiM8izkQwYy11nBJoGkDc3vyMqBPwmYJQ4LlWlFDQU4jmzCYh8BN2H13ziE1ifEsPtTUen5bRy3eHCX5cBoof065M4y6AGI92l9RIcRGto/nb0mll2IoFkegAa8DzuquUJoGfyf5u++4Yh5RUXSK1qrTLMy2g0v3jr3k0HSvsCuf1PMb28P52ioxr/T26p2w/Fa9+j1EKAXG/67NcGm4sOu0cchq796+k+5XOfsqlRwasxA0thtnirqZB4GBkZxSj/VQfAtEqsA+/Gczz1kavtqNvzVuzlB4MhYhYFlAw+/zdbglqip6KBzeqfBziTy49ZfGCC5AvZ2qIJ5s8kZWPkqBthUNIT3hnnJ0Bt6VGUS0jxHa7q+vLLPZAH+N+OO19ks41PyG+uq6MS5tsJxhTZFuJwPgz0Z+DuE+Hj+/sUDbS8ktg8/B5uA06DGFf5xafgZNgjffzf1UppDiLWTaLQ9xqv0B89pIbiLobccVVfPXCw9JybmmL1skyVdgiS0cspxD9UDF2o/8t/Mlyt+K6Z5k=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
