travis:
  secure:
    BINSTAR_TOKEN: SFP1K+amphCdr9CfAH2QIWAlEufLpkvD2qQCWromFp2k+CQtUJZEJICswaJYMetnY7QZ7rGvKfyWPhIEDTNTlMNgGeRS4+ciYuSXCuVXxXg1ulJ+G2xqRRpPWG4yFlm9JNpmj89xYVKtFe5qDDgmfAs+UwElaSeXzUeAQ3RzUor7ujGdd6ZcBpvEOJa8mIiD+vGL6v781JnAxw1HTtvd3ezTh5ntW18QOXaxrOWJFl3LnKfXp9FKGiXFAAZAfwWBbi7ZqM/n27YQit6jzzBilOw6Gtwt87zbZp08pnrA6fDHmfMc0K7FrCQh0waz1+h6iAea3GIV32mmAaNUT99c7CDQA0qEAQn3dvozENq0OCWgLsLxmMEZK5ROymdO6ZdodUgoYmEs9GYlVfsCsuzOYHfJYqqcQmKbdCy2yqAHEQO/trnp1VqA87UvYI6tm2o6EVJBMYjd/ooNY5nR2inTk0eRah1RRLWeyf8hvUlF5MJFQjPBpl8Vch5I5iPOLFEAFmEYw5oKoY3ndDu2LOKjJNfeBgFd62D5fb/Wr6I2zz2BhrFefOwYuxCUN29cGR3sNyni4/q24ie1BUqVIZd/Yq2+r8yPF7g/XuUMY/8ulKogxYaqzrOYxWz8ja9jOTlq1j72fPkwF5cL0ZNf3vRnMLtr/i97mHFqQ0UPQbvcA9w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
